select '线下'            部门,
       '区域'            无,
       h.VC_XIANGMCDBM 办事处,
       t1.VC_YEJGSYWY  客户经理,
       h.VC_HETBH      合同编号,
       '无'             合同归属,
       t2.VC_KEHMC     客户编号,
       '无'             承租人年龄,
       '无'             承租人身份证,
       '无'             承租人手机,
       t2.VC_SHENGF    承租人省份,
       '无'             承租人地址,
       '无'             配偶姓名,
       '无'             配偶手机,
       h.VC_DANBLXBQ   担保类型,
       '无'             核实更新其他联系方式,
       t3.VC_KAIHZH    还款借记卡账户,
       '无'             承租人信审评级,
       '现代物流'          业务类型,
       '手工添加'          产品类型,
       '无'             产品方案,
       t4.DEC_SHEBJG   设备金额,
       '无'              加融配件费,
       '无'              加融保险,
       '无'              加融购置税,
        (select DEC_JIASHJ from fm_jiaoyjgfyx where VC_FEIYLX = '101' and t5.NU_JIAOYJGID = t4.NU_ID) 综合首付,
       t4.DEC_ZULGSBJBL  融资金额,
       (select sum(j2.DEC_BAOZJDK) from FM_JIAOYJG j1 left join fm_jiaoyjgywxjl j2 on j1.NU_ID = j2.NU_JIAOYJGID where j1.VC_CESZTBH = h.VC_KEHBH) 保证金,
        t4.DEC_SPEC_IRR   IRR,
        t4.DEC_JINGRZE    净融资额,
       t4.DEC_HANSGP     含税GP,
       t4.DEC_GP_AFTER_TAX   税后GP,
       t4.XDEC_QUDFJE       渠道费,
       t4.XDEC_ZIXFWFSR    厂商咨询服务费,
       t4.XDEC_SHOUXF       厂商手续费,
       '无'                  贴息服务费,
       h.VC_ZULLXBQ          租赁类型,
       t4.VC_LILFDLX        利率浮动类型,
       '无'                  调息基准日,
       t6.NU_ZUQ            租期,
       h.DT_YUEDQZR           起租日期,
        t7.end_date         结束日期,
        t4.NU_HUANZFS       还租方式,
       t4.NU_MEIYCFR        当月计划还款日,
       t4.DEC_ZULHTZJE      租金总额,
t8.VC_JIAOCXSF              交叉销售方,
        t4.XDEC_DAILSBZJBL      代理商,
       '无'              代理商所属省份,
       '无'              代理商在线状态,
       '无'              申请提报标识,
       h.VC_GUAKS           车牌方名称,
       '无'              信审专员,
       '无'              高级信审专员,
       '无'              是否电核
from BZ_HETJBXX h
         left join BZ_YEJGS t1 on h.VC_HETBH = t1.VC_HETBH
         left join CM_JIGKH t2 on h.VC_KEHBH = t2.VC_KEHBH
         left join CM_KEHYHZH t3 on h.VC_KEHBH = t3.VC_KEHBH
         left join FM_JiaoYJG t4 on h.VC_KEHBH = t4.VC_CESZTBH
left join fm_jiaoyjgfyx t5 on t4.NU_ID = t5.NU_JIAOYJGID
left join FM_JIAOYJGZJDZXX t6 on t4.NU_ID = t6.NU_JIAOYJGID
left join rpt_contract_info t7 on h.VC_HETBH = t7.CONTRACT_ID and t7.HIS_DATE ='2022-01-10'
left join BZ_HETJCXS t8 on h.VC_HETBH = t8.VC_HETBH
where h.VC_HETBH = 'KFL21100058001';